config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'


  resources :posts, except: [:destroy] do
  	member do
  		post '/vote', to: 'posts#vote'
  	end
  	resources :comments, only: [:create]
  end

  resources :comments, only: [] do
    member do
      post '/vote', to: 'comments#vote'
    end
  end

  resources :categories, only: [:show, :new, :create]
  resources :users, except: [:index]
end

app/models/comment.rb
class Comment < ActiveRecord::Base

	include VoteableHenryk

	belongs_to :creator, class_name: "User", foreign_key: "user_id"
	belongs_to :post
	has_many :votes, as: :voteable

	scope :list, -> { all.sort_by{ |x| x.total_votes }.reverse }

	validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find_by(slug: params[:post_id])
		@comment = @post.comments.build(params.require(:comment).permit(:body))
		@comment.creator = current_user

		if @comment.save
			flash[:notice] = "Your comment has been created."
			redirect_to post_path(@post)
		else
			render "posts/show"
		end
	end

	def vote
		@comment = Comment.find(params[:id])
		@vote = @comment.votes.create(vote: params[:vote], creator: current_user)

    if @vote.valid?
      flash[:notice] = "Your vote was counted."
    else
      flash[:error] = "You can only vote for <strong>that</strong> once.".html_safe
    end

    respond_to do |format|
    	format.html { redirect_to :back }
    	format.js
    end
	end
end

app/views/comments/_comment.html.erb
<div class="row">
	<% if logged_in? %>
		<div class="span0 well">
			<%= link_to vote_comment_path(comment, vote: true), title: "good", method: "post", remote: true do %>
				<i class="icon-arrow-up"></i>
			<% end %>
			<br />
			<span id="comment_<%= comment.id %>_votes">
				<%= comment.total_votes %>
			</span>
			<br />
			<%= link_to vote_comment_path(comment, vote: false), title: "bad", method: "post", remote: true do %>
				<i class="icon-arrow-down"></i>
			<% end %>
		</div>
	<% end %>

  <div class="well span8">
  	<em>"<%= comment.body %>"</em>
  	<br/>
  	<span class="quiet">by</span> <%= comment.creator.username %>
  	<small>at <%= display_datetime(comment.created_at) %></small>
  </div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
	$("#comment_<%= @comment.id %>_votes").html("<%= Vote.total_votes(@comment) %>");
<% else %>
	alert("<%= flash[:error] %>");
<% end %>