config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'


  resources :posts, except: [:destroy] do
  	member do
  		post '/vote', to: 'posts#vote'
  	end
  	resources :comments, only: [:create]
  end

  resources :comments, only: [] do
    member do
      post '/vote', to: 'comments#vote'
    end
  end

  resources :categories, only: [:show, :new, :create]
  resources :users, except: [:index]
end

app/models/post.rb
class Post < ActiveRecord::Base

	include VoteableHenryk
	include SluggableHenryk

	belongs_to :creator, class_name: "User", foreign_key: "user_id"
	has_many :comments, dependent: :destroy
	has_many :post_categories
	has_many :categories, :through => :post_categories, dependent: :destroy
	has_many :votes, as: :voteable

	scope :list, -> { all.sort_by{ |x| x.total_votes }.reverse }

	validates :title, presence: true, length: {minimum: 5}
	validates :description, presence: true
	validates :url, presence: true, uniqueness: true

	sluggable_column :title

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
	before_action :require_modifiable, only: [:edit, :update, :destroy]
  skip_before_action :require_user, only: [:index, :show]

  helper_method :can_modify?

  def index
    @posts = Post.list
    respond_to do |format|
      format.html
      format.json { render json: @posts }
      format.xml { render xml: @posts }
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.list
  end

  def new
  	@post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

  	if @post.save
  		flash[:notice] = "Your post was created."
  		redirect_to posts_path
  	else
  		render "new"
  	end
  end

  def edit
  end

  def update
  	if @post.update(post_params)
  		flash[:notice] = "This post was updated."
  		redirect_to posts_path
  	else
  		render "edit"
  	end
  end

  def vote
    @vote = @post.votes.create(vote: params[:vote], creator: current_user)

    if @vote.valid?
      flash[:notice] = "Your vote was counted."
    else
      flash[:error] = "You can only vote for <strong>that</strong> once.".html_safe
    end

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  private

  def post_params
  	params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
  	@post = Post.find_by(slug: params[:id])
  end

  def can_modify?
    (is_admin? or (current_user and @post and @post.creator == current_user))
  end

  def require_modifiable
    access_denied unless can_modify?
  end
end

app/views/posts/_form.html.erb
<%= render "shared/errors", obj: @post %>

<%= form_for @post do |f| %>
  <div class="control-group">
  	<%= f.label :title %>
  	<%= f.text_field :title %>
  </div>
  <div class="control-group">
  	<%= f.label :url %>
  	<%= f.text_field :url %>
  </div>
  <div class="control-group">
  	<%= f.label :description %>
  	<%= f.text_area :description, rows: 5 %>
  </div>
  <div class="control-group">
    <%= f.label "Categories" %>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  </div>

  <br>
  <%= f.submit @post.new_record? ? "Create Post" : "Edit Post", class: "btn btn-primary" %>
<% end %>

app/views/posts/_post.html.erb
<div class="row">
	<% if logged_in? %>
	<div class="span0 well">
		<%= link_to vote_post_path(post, vote: true), title: "good", method: "post", remote: true do %>
			<i class="icon-arrow-up"></i>
		<% end %>
		<br />
		<span id="post_<%= post.id %>_votes">
			<%= post.total_votes %>
		</span>
		<br />
		<%= link_to vote_post_path(post, vote: false), title: "bad", method: "post", remote: true do %>
			<i class="icon-arrow-down"></i>
		<% end %>
	</div>
	<% end %>

	<div class="span8 well">
		<p>
			<%= render post.categories %>
		</p>
		<p>
			<%= link_to post.title, fix_url(post.url) %>
		</p>
		<p><%= post.description %></p>
		<p>
			<span class="quiet">posted by</span> <%= post.creator.username %>
			<small>at <%= display_datetime(post.created_at) %></small>
		</p>
		<small>
			<span>
				<%= link_to "#{post.comments.size} comments", post_path(post) %>
			</span>
		</small>
	</div>
</div>

app/views/posts/edit.html.erb
<%= render "shared/content_title", title: "Edit this post" %>

<div class="well">
	<%= render "form" %>
</div>

app/views/posts/index.html.erb
<%= render "shared/content_title", title: "All posts!" %>

<% @posts.each do |post| %>
	<%= render "post", post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render "shared/content_title", title: "Create a post" %>

<div class="well">
	<%= render "form" %>
</div>

app/views/posts/show.html.erb
<% if can_modify? %>
	<p class="pull-right">
		[<%= link_to "edit", edit_post_path(@post) %>]
	</p>
<% end %>

<p>
	<%= render @post.categories %>
</p>
<h4><%= link_to @post.title, fix_url(@post.url) %></h4>
<p>
	<%= @post.description %>
</p>

<hr/>

<% if logged_in? %>
	<%= form_for [@post, @comment] do |f| %>
		<%= render "shared/errors", obj: @comment %>

		<div class="control-group">
			<%= f.label :body, "Leave a comment" %>
			<%= f.text_area :body, rows: 5, class: "span4" %>
		</div>

		<%= f.submit "Create comment", class: "btn btn-primary" %>
	<% end %>
<% end %>

<h5>Comments:</h5>

<% @comments.each do |comment| %>
	<%= render "comments/comment", comment: comment %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
	$("#post_<%= @post.id %>_votes").html("<%= Vote.total_votes(@post) %>");
<% else %>
	alert("<%= flash[:error] %>");
<% end %>